### ISSUE TITLE
[JS] Get recipe results from spoonacular API

### ISSUE THREAD

**Issue by hayleyarodgers** [hayleyarodgers/recipe-finder#9]
- [x] Fetch data from spoonacular API 
- [x] Turn search into something that spoonacular API can understand
- [x] Get data from spoonacular → specifically, a list of recipe names that each contain the ingredients specified by the user

**Comment by hayleyarodgers** [comment]
Note that we don't need the full ingredients or instructions from spoonacular—my understanding is that all we need from spoonacular is potential recipes that we can then enter as our search term into youtube

**Comment by lukesudom** [comment]
The search fields now refresh when being submitted. We can also generate a unique URL based off the input fields - note only one input field is required
